### ISSUE TITLE
Multiple UPNP devices detected on server, only one Airplay source displayed

### ISSUE THREAD

**Issue by mholst** [provegard/airpnp#1]
The server detects two UPNP devices, however, the iPhone only displays one external Airplay device.

The server detection is verified when running server in non-deamonized mode.

**Comment by provegard** [comment]
Hi Morten! I know what the problem is and I have a fix ready. I will take this as an opportunity to get some integration tests around this running, but it hopefully won't take long!

**Comment by mholst** [comment]
Perfekt. Im looking forward to testing the fix. Just let me know.
